"""RESTful endpoints for public-square posts and correction feedback."""

from fastapi import APIRouter, Depends, HTTPException, Query, status
from sqlalchemy.orm import Session

from app import models
from app.crud import feedback as feedback_crud
from app.crud import post as post_crud
from app.database import get_db
from app.schemas.feedback import FeedbackCreate, FeedbackLogOut
from app.schemas.post import PostCreate, PostFeedOut, PostOut


router = APIRouter(tags=["posts"])


@router.post(
    "/api/agents/{agent_id}/posts",
    response_model=PostOut,
    status_code=status.HTTP_201_CREATED,
)
def create_agent_post(
    agent_id: int,
    post_in: PostCreate,
    db: Session = Depends(get_db),
) -> PostOut:
    """Create a simulated post from an agent."""
    db_agent = db.get(models.Agent, agent_id)
    if db_agent is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Agent not found.",
        )

    return post_crud.create_post(db, agent_id, post_in)


@router.get("/api/posts", response_model=list[PostFeedOut])
def get_public_feed(
    skip: int = Query(0, ge=0),
    limit: int = Query(100, ge=1, le=200),
    db: Session = Depends(get_db),
) -> list[PostFeedOut]:
    """Return the public-square feed, newest posts first."""
    posts = post_crud.get_posts(db, skip=skip, limit=limit)
    return [
        PostFeedOut(
            id=post.id,
            agent_id=post.agent_id,
            agent_name=post.agent.agent_name,
            content=post.content,
            timestamp=post.timestamp,
        )
        for post in posts
    ]


@router.post(
    "/api/posts/{post_id}/feedback",
    response_model=FeedbackLogOut,
    status_code=status.HTTP_201_CREATED,
)
def create_post_feedback(
    post_id: int,
    feedback_in: FeedbackCreate,
    db: Session = Depends(get_db),
) -> FeedbackLogOut:
    """Record user correction feedback for a post from the user's own agent."""
    db_post = post_crud.get_post(db, post_id)
    if db_post is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Post not found.",
        )

    if db_post.agent.user_id != feedback_in.user_id:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Users can only correct posts generated by their own agent.",
        )

    return feedback_crud.create_feedback_log(db, db_post, feedback_in)
