"""SQLAlchemy models for Loop's research data core."""

from datetime import datetime
from uuid import uuid4

from sqlalchemy import (
    Boolean,
    JSON,
    Column,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.orm import relationship

from .database import Base


def utc_now_seconds() -> datetime:
    """Return the current UTC time with second-level precision."""
    return datetime.utcnow().replace(microsecond=0)


class ProbeResponse(Base):
    """Questionnaire and counterfactual probe answer for M1-M6 validation."""

    __tablename__ = "probe_responses"

    response_id = Column(
        String(36),
        primary_key=True,
        default=lambda: str(uuid4()),
        index=True,
    )
    user_id = Column(String(128), nullable=False, index=True)
    probe_set = Column(String(64), nullable=False, index=True)
    probe_id = Column(String(128), nullable=False, index=True)
    answer = Column(JSON, nullable=False)
    responder = Column(String(16), nullable=False, index=True)
    timestamp = Column(DateTime, default=utc_now_seconds, nullable=False, index=True)


class User(Base):
    """Laboratory user with questionnaire-derived personality and value data."""

    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    username = Column(String(64), unique=True, index=True, nullable=False)
    password_hash = Column(String(255), nullable=False)
    created_at = Column(DateTime, default=utc_now_seconds, nullable=False)
    mbti_type = Column(String(16), nullable=True)
    big_five_scores = Column(JSON, nullable=True)
    schwartz_values = Column(JSON, nullable=True)
    autobiography = Column(Text, nullable=True)
    core_memory = Column(
        JSON,
        default=lambda: {
            "persona_traits": "",
            "key_relationships": "",
            "current_goals": "",
        },
        nullable=True,
    )

    agent = relationship("Agent", back_populates="user", uselist=False)
    feedback_logs = relationship("FeedbackLog", back_populates="user")


class Agent(Base):
    """Virtual agent generated from a user's profile and questionnaire data."""

    __tablename__ = "agents"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    agent_name = Column(String(128), nullable=False)
    system_prompt_base = Column(Text, nullable=False)
    is_npc = Column(Boolean, default=False, nullable=False, index=True)

    user = relationship("User", back_populates="agent")
    posts = relationship("Post", back_populates="agent")
    chat_logs = relationship("ChatLog", back_populates="agent")
    relationships_from = relationship(
        "Relationship",
        back_populates="source_agent",
        foreign_keys="Relationship.agent_id_1",
    )
    relationships_to = relationship(
        "Relationship",
        back_populates="target_agent",
        foreign_keys="Relationship.agent_id_2",
    )
    reflection_events = relationship("ReflectionEvent", back_populates="agent")
    event_logs = relationship("EventLog", back_populates="agent")
    evaluations = relationship("Evaluation", back_populates="agent")


class EventLog(Base):
    """Append-only event store for reconstructing agent timelines."""

    __tablename__ = "event_logs"

    event_id = Column(Integer, primary_key=True, index=True)
    timestamp = Column(DateTime, default=utc_now_seconds, nullable=False, index=True)
    agent_id = Column(Integer, ForeignKey("agents.id"), nullable=False, index=True)
    branch_id = Column(String(128), default="main", nullable=False, index=True)
    event_type = Column(String(128), nullable=False, index=True)
    payload = Column(JSON, nullable=False)

    agent = relationship("Agent", back_populates="event_logs")


class Relationship(Base):
    """Directed social affinity between two virtual agents."""

    __tablename__ = "relationships"
    __table_args__ = (
        UniqueConstraint(
            "agent_id_1",
            "agent_id_2",
            name="uq_relationship_agent_pair",
        ),
    )

    id = Column(Integer, primary_key=True, index=True)
    agent_id_1 = Column(Integer, ForeignKey("agents.id"), nullable=False, index=True)
    agent_id_2 = Column(Integer, ForeignKey("agents.id"), nullable=False, index=True)
    affinity_score = Column(Float, default=0.0, nullable=False)

    source_agent = relationship(
        "Agent",
        back_populates="relationships_from",
        foreign_keys=[agent_id_1],
    )
    target_agent = relationship(
        "Agent",
        back_populates="relationships_to",
        foreign_keys=[agent_id_2],
    )


class Post(Base):
    """Autonomous public-square post generated by a virtual agent."""

    __tablename__ = "posts"

    id = Column(Integer, primary_key=True, index=True)
    agent_id = Column(Integer, ForeignKey("agents.id"), nullable=False, index=True)
    content = Column(Text, nullable=False)
    timestamp = Column(DateTime, default=utc_now_seconds, nullable=False)

    agent = relationship("Agent", back_populates="posts")
    feedback_logs = relationship("FeedbackLog", back_populates="post")


class FeedbackLog(Base):
    """User correction log used as ground truth for continual learning."""

    __tablename__ = "feedback_logs"

    id = Column(Integer, primary_key=True, index=True)
    post_id = Column(Integer, ForeignKey("posts.id"), nullable=False, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    original_text = Column(Text, nullable=False)
    corrected_text = Column(Text, nullable=False)
    timestamp = Column(DateTime, default=utc_now_seconds, nullable=False)
    context_embedding_id = Column(String(255), nullable=True)

    post = relationship("Post", back_populates="feedback_logs")
    user = relationship("User", back_populates="feedback_logs")


class ChatLog(Base):
    """Daily private sync conversation between a user and their agent."""

    __tablename__ = "chat_logs"

    id = Column(Integer, primary_key=True, index=True)
    agent_id = Column(Integer, ForeignKey("agents.id"), nullable=False, index=True)
    branch_id = Column(String(128), default="main", nullable=False, index=True)
    session_id = Column(
        String(64),
        default="default_session",
        nullable=False,
        index=True,
    )
    topic = Column(String(64), default="general", nullable=False, index=True)
    experiment_mode = Column(
        String(32),
        default="mode_alpha",
        nullable=False,
        index=True,
    )
    user_message = Column(Text, nullable=False)
    agent_reply = Column(Text, nullable=False)
    timestamp = Column(DateTime, default=utc_now_seconds, nullable=False)

    agent = relationship("Agent", back_populates="chat_logs")


class Evaluation(Base):
    """Blind-test authenticity rating from a public evaluator."""

    __tablename__ = "evaluations"

    id = Column(Integer, primary_key=True, index=True)
    agent_id = Column(Integer, ForeignKey("agents.id"), nullable=False, index=True)
    evaluator_relation = Column(String(32), nullable=False)
    authenticity_score = Column(Integer, nullable=False)
    qualitative_feedback = Column(Text, nullable=True)
    sampled_chat_log_ids = Column(JSON, nullable=True)
    timestamp = Column(DateTime, default=utc_now_seconds, nullable=False, index=True)

    agent = relationship("Agent", back_populates="evaluations")


class ReflectionEvent(Base):
    """Layered reflection tree node derived during sleep consolidation."""

    __tablename__ = "reflection_events"

    id = Column(Integer, primary_key=True, index=True)
    agent_id = Column(Integer, ForeignKey("agents.id"), nullable=False, index=True)
    level = Column(String(32), nullable=False, index=True)
    content = Column(Text, nullable=False)
    source_record_count = Column(Integer, default=0, nullable=False)
    created_at = Column(DateTime, default=utc_now_seconds, nullable=False, index=True)
    reflected_at = Column(DateTime, nullable=True, index=True)

    agent = relationship("Agent", back_populates="reflection_events")
