"""SQLAlchemy models for Loop's research data core."""

from datetime import datetime

from sqlalchemy import JSON, Column, DateTime, ForeignKey, Integer, String, Text
from sqlalchemy.orm import relationship

from .database import Base


def utc_now_seconds() -> datetime:
    """Return the current UTC time with second-level precision."""
    return datetime.utcnow().replace(microsecond=0)


class User(Base):
    """Laboratory user with questionnaire-derived personality and value data."""

    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    username = Column(String(64), unique=True, index=True, nullable=False)
    password_hash = Column(String(255), nullable=False)
    created_at = Column(DateTime, default=utc_now_seconds, nullable=False)
    mbti_type = Column(String(16), nullable=True)
    big_five_scores = Column(JSON, nullable=True)
    schwartz_values = Column(JSON, nullable=True)
    autobiography = Column(Text, nullable=True)

    agent = relationship("Agent", back_populates="user", uselist=False)
    feedback_logs = relationship("FeedbackLog", back_populates="user")


class Agent(Base):
    """Virtual agent generated from a user's profile and questionnaire data."""

    __tablename__ = "agents"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    agent_name = Column(String(128), nullable=False)
    system_prompt_base = Column(Text, nullable=False)

    user = relationship("User", back_populates="agent")
    posts = relationship("Post", back_populates="agent")
    chat_logs = relationship("ChatLog", back_populates="agent")


class Post(Base):
    """Autonomous public-square post generated by a virtual agent."""

    __tablename__ = "posts"

    id = Column(Integer, primary_key=True, index=True)
    agent_id = Column(Integer, ForeignKey("agents.id"), nullable=False, index=True)
    content = Column(Text, nullable=False)
    timestamp = Column(DateTime, default=utc_now_seconds, nullable=False)

    agent = relationship("Agent", back_populates="posts")
    feedback_logs = relationship("FeedbackLog", back_populates="post")


class FeedbackLog(Base):
    """User correction log used as ground truth for continual learning."""

    __tablename__ = "feedback_logs"

    id = Column(Integer, primary_key=True, index=True)
    post_id = Column(Integer, ForeignKey("posts.id"), nullable=False, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    original_text = Column(Text, nullable=False)
    corrected_text = Column(Text, nullable=False)
    timestamp = Column(DateTime, default=utc_now_seconds, nullable=False)
    context_embedding_id = Column(String(255), nullable=True)

    post = relationship("Post", back_populates="feedback_logs")
    user = relationship("User", back_populates="feedback_logs")


class ChatLog(Base):
    """Daily private sync conversation between a user and their agent."""

    __tablename__ = "chat_logs"

    id = Column(Integer, primary_key=True, index=True)
    agent_id = Column(Integer, ForeignKey("agents.id"), nullable=False, index=True)
    user_message = Column(Text, nullable=False)
    agent_reply = Column(Text, nullable=False)
    timestamp = Column(DateTime, default=utc_now_seconds, nullable=False)

    agent = relationship("Agent", back_populates="chat_logs")
